### PR TITLE
Support Ng ultrawarm

### PR DESCRIPTION
**Pull request by ngamber**
## what
* Adds support for AWS Elasticsearch ultrawarm instance type

## why
Needed to deploy clusters with ultrawarm node types

## references
* https://aws.amazon.com/about-aws/whats-new/2020/05/aws-announces-amazon-elasticsearch-service-ultrawarm-general-availability/
https://github.com/terraform-providers/terraform-provider-aws/pull/12668

### CODE REVIEW

**Comment by Gowiem** [comment]
@ngamber Looks like tests are failing because the ES resource doesn't like one of your defaults: 

```
Error: expected cluster_config.0.warm_count to be in the range (2 - 150), got 0

  on ../../main.tf line 122, in resource "aws_elasticsearch_domain" "default":
 122: resource "aws_elasticsearch_domain" "default" {
```

Would you mind updating that default to be `null` and we'll give that a shot?

**Comment by aknysh** [comment]
superseded by #71

**Pull request closed without merging**
