### PR TITLE
Adds *_hostname_enabled vars for explicit opt-in to hostnames

### LINKED ISSUE #13: module requires two phase apply due to `value of count cannot be computed`
## what

While trying to test a new module, which depends on this one, I added example usage:

```
module "vpc" {
  source    = "git::https://github.com/cloudposse/terraform-aws-vpc.git?ref=master"
  namespace = "example"
  stage     = "dev"
  name      = "app"
}

resource "aws_route53_zone" "default" {
  name = "cp-example.com"
}

module "subnets" {
  source             = "git::https://github.com/cloudposse/terraform-aws-dynamic-subnets.git?ref=master"
  namespace          = "example"
  stage              = "dev"
  name               = "app"
  region             = "us-east-1"
  vpc_id             = "${module.vpc.vpc_id}"
  igw_id             = "${module.vpc.igw_id}"
  cidr_block         = "10.0.0.0/16"
  availability_zones = ["us-east-1a", "us-east-1b"]
}

module "elasticsearch" {
  source                  = "git::https://github.com/cloudposse/terraform-aws-elasticsearch.git?ref=tags/0.1.5"
  namespace               = "example"
  stage                   = "dev"
  name                    = "es"
  dns_zone_id             = "${aws_route53_zone.default.id}"
  security_groups         = []
  vpc_id                  = "${module.vpc.vpc_id}"
  subnet_ids              = ["${module.subnets.public_subnet_ids}"]
  zone_awareness_enabled  = "true"
  elasticsearch_version   = "6.2"
  instance_type           = "t2.small.elasticsearch"
  instance_count          = 4
  kibana_subdomain_name   = "example-kibana-es"
  encrypt_at_rest_enabled = "false"
  ebs_volume_size         = 10
  iam_actions             = ["es:*"]
  iam_role_arns           = ["*"]
}

module "elasticsearch-cleanup" {
  source               = "../"
  es_endpoint          = "${module.elasticsearch.domain_endpoint}"
  es_domain_arn        = "${module.elasticsearch.domain_arn}"
  es_security_group_id = "${module.elasticsearch.security_group_id}"
  vpc_id               = "${module.vpc.vpc_id}"
  enabled              = "true"
  namespace            = "example"
  stage                = "dev"
  schedule             = "rate(5 minutes)"
}
```

which failed with the below error:

```
Error: Error running plan: 2 error(s) occurred:

* module.elasticsearch.module.domain_hostname.aws_route53_record.default: aws_route53_record.default: value of 'count' cannot be computed
* module.elasticsearch.module.kibana_hostname.aws_route53_record.default: aws_route53_record.default: value of 'count' cannot be computed
```
This happens because the ID cannot be computed until after creation.
The workaround for this was using a two stage apply and passing the `-target` option.

### PR DESCRIPTION
**Pull request by Gowiem**
## what
* Adds `domain_hostname_enabled` and `kibana_hostname_enabled` var flags to fix an issues with `count` when dns_zone_id is not being passed static. 

## why
* Implicit opt-in through checking dns_zone_id was causing folks problems as count / enabled need to be calculated during the plan which caused using `-target`. 
* This fixes needing a targeted apply when passing dns_zone_id from a resource or module reference. 

## references
* Fixes + Closes #13 
* Discussion in SweetOps: https://sweetops.slack.com/archives/CB6GHNLG0/p1600294860394500

### CODE REVIEW

**Review by jamengual — APPROVED** [review]

**Comment by aknysh** [comment]
@Gowiem I'm going to update the Terratest to prevent failures like that

**Comment by Gowiem** [comment]
@aknysh I believe the failure here was because I added a new flag that is off by default and therefore the previous way of enabling hostnames was ignored, subdomains were not created, and the actual tests that check subdomain output failed. Are you thinking there is another issue outside of that regarding the need for unique subdomain names or something else?

**Comment by aknysh** [comment]
> @aknysh I believe the failure here was because I added a new flag that is off by default and therefore the previous way of enabling hostnames was ignored, subdomains were not created, and the actual tests that check subdomain output failed. Are you thinking there is another issue outside of that regarding the need for unique subdomain names or something else?

Yes, we need to add random attributes to the test, because the prev failure was b/c some resources with the same names already existed from the previous failures.
I'll add `context.tf` as well

**Comment by Gowiem** [comment]
@aknysh Gotcha. Do your thing and thanks for the assist.

**Review by aknysh — APPROVED** [review]

**Pull request merged**
