### PR TITLE
Support ebs_throughput to enable using of gp3

### PR DESCRIPTION
**Pull request by dm3ch**
## what
* Support ebs volume thoughtput option

## why
* Cause documentation says that this option is required for gp3 volume type

## references
* #141 
* https://github.com/cloudposse/terraform-aws-elasticsearch/issues/110

### CODE REVIEW

**Comment by goruha** [comment]
@dm3ch we can not run tests for this PR at the moment.
Can you pull the latest changes from the master branch with the fix for tests?

**Comment by dm3ch** [comment]
@goruha Done

**Comment by goruha** [comment]
@dm3ch now this PR duplicates PR https://github.com/cloudposse/terraform-aws-elasticsearch/pull/149
The PR contains issues that break our tests.

Can you leave in the PR only code related to `ebs_throughput`  support

Thanks.

**Comment by dm3ch** [comment]
@goruha Dropped unwanted changes

**Review by goruha — APPROVED** [review]

**Comment by goruha** [comment]
@dm3ch LGTM

Thanks for your contribution!

**Pull request merged**
