### PR TITLE
Allow use of 3 availability zones

### PR DESCRIPTION
**Pull request by fliphess**
Allow use of 3 availability zones after terraform-providers/terraform-provider-aws#9398

### CODE REVIEW

**Comment by aknysh** [comment]
thanks @fliphess 

Looks good, but please rebuild README by executing these commands:

```
make init
make readme/deps
make readme
```

It will add the new variables and outputs to `README.md` automatically.

In general, any changes to README should be made in `README.yaml` (not in this case), and after that executing the commands above will rebuild `README.yaml` into `README.md` and add all new variables and outputs to `README.md`

thanks

**Comment by aknysh** [comment]
also please take a look at this `terraform apply` error (from the tests):

```
TestExamplesComplete 2019-07-22T13:38:33Z command.go:121: Error: Unsupported argument                                                                                                     
TestExamplesComplete 2019-07-22T13:38:33Z command.go:121:                                                                                                                                 
TestExamplesComplete 2019-07-22T13:38:33Z command.go:121:   on ../../main.tf line 129, in resource "aws_elasticsearch_domain" "default":                                                  
TestExamplesComplete 2019-07-22T13:38:33Z command.go:121:  129:       zone_awareness_enabled  = var.zone_awareness_enabled                                                                
TestExamplesComplete 2019-07-22T13:38:33Z command.go:121:                                                                                                                                 
TestExamplesComplete 2019-07-22T13:38:33Z command.go:121: An argument named "zone_awareness_enabled" is not expected here.                                                                
TestExamplesComplete 2019-07-22T13:38:33Z command.go:121:                                                                                                                                 
TestExamplesComplete 2019-07-22T13:38:33Z retry.go:80: Returning due to fatal error: FatalError{Underlying: exit status 1}                                                                
```

**Comment by fliphess** [comment]
Ah thanks for pointing out where to look :) 

I'll look into it, sorry for not looking after the tests and adjust correctly, I was at work and was hoping for a quick win :)

**Comment by aknysh** [comment]
thanks @fliphess 
feel free to add another AZ here https://github.com/cloudposse/terraform-aws-elasticsearch/blob/master/examples/complete/fixtures.us-west-1.tfvars#L9

**Comment by fliphess** [comment]
Did the last testrun succeed? I wasn't able to view the output......

**Comment by aknysh** [comment]
@fliphess 
we need to look into this in more details.
your changes are correct, but our tests use `us-west-1` region that has only 2 AZs per account (and the AZs are different for diff accounts), so currently we can't test with 3 AZs in `us-west-1`

**Comment by fliphess** [comment]
Hey @aknysh, Let me know what you have in mind, for now, I reverted the last commit that adds the third AZ so the test will succeed.

I think how to test in multiple availability zones is mostly a Cloudposse decision and not a a community effort as it's your billing and your AWS account :) 

(Thanks btw for the high quality terraform modules, highly appreciated)

**Comment by fliphess** [comment]
Maybe merge this PR and start a new issue to come up with a solution for the missing third availability zone? Keep me posted :)

**Pull request merged**
