### PR TITLE
[GH Issue 85] Support Audit Logging

### LINKED ISSUE #85: Support Audit Logging
There are currently four types of logs supported by Terraform Elasticsearch: `INDEX_SLOW_LOGS`, `SEARCH_SLOW_LOGS`, `ES_APPLICATION_LOGS`, and `AUDIT_LOGS`. The Cloudposse module currently supports the first of these log types, but does not allow you to enable `AUDIT_LOGS`.

### PR DESCRIPTION
**Pull request by neuroticnetworks**
## what
*  This PR enables `AUDIT_LOGS` support in the CloudPosse ES Module.

## why
* There are currently four types of logs supported by Terraform Elasticsearch: `INDEX_SLOW_LOGS`, `SEARCH_SLOW_LOGS`, `ES_APPLICATION_LOGS`, and `AUDIT_LOGS` (xref **log_publishing_options** [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#argument-reference)) The CloudPosse module currently supports the first of these log types, but does not allow you to enable `AUDIT_LOGS`.

## references
- closes #85 
- closes #84

### CODE REVIEW

**Comment by neuroticnetworks** [comment]
Not sure how to interpret that failure, but happy to address any issues if there's anything I can do. Please let me know!

**Comment by Gowiem** [comment]
@neuroticnetworks not your fault 😅  We recently changed the bats test to validate that all Cloud Posse modules are using the Terraform registry syntax > the github URL synxtax. 

If you can update to that then that would be great and we'll get this shipped 👍

**Comment by neuroticnetworks** [comment]
Not sure what to make of this latest failure; I don't think my syntax is wrong or that I missed any of the invocations?

**Review by Nuru — APPROVED** [review]

**Pull request merged**
