### PR TITLE
support the node-to-node encryption feature

### PR DESCRIPTION
**Pull request by Shogan**
## what
* My PR adds support for the optional node-to-node encryption feature for AWS Elasticsearch 

## why
* I need to use in my infrastructure which I'm spinning up with your module

### CODE REVIEW

**Comment by Shogan** [comment]
Thanks @osterman - I'm on a windows box, so I spun up a linux machine to do the make rebuild for README and applied the terraform fmt. Hope it's all good now. Cheers!

**Comment by osterman** [comment]
Oh, sorry for the hassle! I wonder if it might work on WSL too.

**Comment by Shogan** [comment]
> Oh, sorry for the hassle! I wonder if it might work on WSL too.

It was no trouble, had a VM already, just booted it up. I'll give WSL a try next time 👍

**Comment by Shogan** [comment]
pulled down the latest module from master to double check and this toggle is working nicely. Thanks for getting the PR merged 👍

**Pull request merged**
