### PR TITLE
Fix Reference to Undeclared Variable

### PR DESCRIPTION
**Pull request by sherifabdlnaby**
## what
- Correct variable name for `var.auto_tune.cron_schedule`

## why
- `cron_expression_for_recurrence` referred to the wrong variable name, with `_` not `.`

### CODE REVIEW

**Comment by sneljo1** [comment]
👍

**Comment by milldr** [comment]
this depends on #167 and #168. We'll get these prioritized internally

**Review by milldr — APPROVED** [review]

**Pull request merged**
