### PR TITLE
Update variables.tf to allow a availability_zone_count of 1

### LINKED ISSUE #158: Fix variable availability_zone_count
### Describe the Bug

The README says

NOTE: To enable [zone awareness](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-zoneawareness) to deploy Elasticsearch nodes into two different Availability Zones, you need to set zone_awareness_enabled to true and provide two different subnets in subnet_ids. If you enable zone awareness for your domain, Amazon ES places an endpoint into two subnets. The subnets must be in different Availability Zones in the same region. If you don't enable zone awareness, Amazon ES places an endpoint into only one subnet. **You also need to set availability_zone_count to 1**.

When I set the value of availability_zone_count to 1 I get an error because in the latest release you didn't correct variables.tf, namely you didn't comment out validation in availability_zone_count

```
variable "availability_zone_count" {
  type        = number
  default     = 2
  description = "Number of Availability Zones for the domain to use."

  **validation {
    condition     = contains([2, 3], var.availability_zone_count)
    error_message = "The availibility zone count must be 2 or 3."
  }**
}

```

### Expected Behavior

When setting availability_zone_count = 1, I shouldn't get an error
 
var.availability_zone_count is 1
The availability zone count must be 2 or 3.

### Steps to Reproduce

set variable
availability_zone_count = 1

### Screenshots

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ManuelMueller1st**
## what

- Update variables.tf to allow a availability_zone_count of 1

## why

- This helps reduce costs for small test clusters.

## references

- `closes #158`

### CODE REVIEW

**Comment by goruha** [comment]
terratest

**Comment by ManuelMueller1st** [comment]
@goruha Hello there! I noticed that you have an issue assigned to you. Is there anything I can do to support you in resolving it? Please let me know if there's anything I can do to help.

**Comment by ManuelMueller1st** [comment]
@jamengual @woz5999 Anything I can do to support you with this request?

**Comment by jamengual** [comment]
could you please update the pr(pull from.main) and run ```make precommit/terraform```

**Comment by ManuelMueller1st** [comment]
> could you please update the pr(pull from.main) and run ```make precommit/terraform```
> 
> 

And now? 😄

**Comment by ManuelMueller1st** [comment]
This project is obviously no longer maintained

**Comment by Gowiem** [comment]
@ManuelMueller1st what do you mean by that? If you get this into a working + passing state, ping me and I will review. We are mostly volunteer maintainers, so try to set expectations around that and there are 200+ modules that we get emails about.

**Pull request closed without merging**
