### PR TITLE
Add cold storage support

### PR DESCRIPTION
**Pull request by dm3ch**
## what
* Add support of configuring `cluster_config.cold_storage_options.enabled`

## why
* Allows enabling support of cold storage

### CODE REVIEW

**Comment by goruha** [comment]
@dm3ch we can not run tests for this PR at the moment.
Can you pull the latest changes from the `master` branch with the fix for tests?

**Comment by dm3ch** [comment]
@goruha Merged existing master

**Comment by goruha** [comment]
@dm3ch now this PR duplicates PR #149 
The PR contains issues that break our tests.

I will close PR 149 and duplicate comments to fix the tests in the current PR.
Could you pls address that fixes so we will be able to merge your changes?

Thanks.

**Comment by goruha** [comment]
@dm3ch now this PR duplicates PR https://github.com/cloudposse/terraform-aws-elasticsearch/pull/149
The PR contains issues that break our tests.

Can you leave in the PR only code related to `cold storage support`

Thanks.

**Comment by dm3ch** [comment]
@goruha Yep, merged the wrong branch.

Now dropped unwanted changes from this PR.

**Comment by dm3ch** [comment]
@goruha I'm not sure how to better fix this test.

I even don't understand why the test tries to enable cold storage if I haven't modified any tests and made it disabled by default.

**Comment by goruha** [comment]
@dm3ch it does not enable cold storage.
I says that it do not  support that cold storage configuration block at all

```
Error: creating Elasticsearch Domain (eg-test-es-test-10332): ValidationException: Your domain's Elasticsearch version does not support cold storage options. Upgrade to Elasticsearch 7.9 or later.
```

I think you have to make this block `dynamic`

**Comment by dm3ch** [comment]
Ok, wrapped to dynamic block

**Review by goruha — APPROVED** [review]

**Comment by goruha** [comment]
@dm3ch LGTM

Thanks for your contribution.

**Pull request merged**
