### PR TITLE
Allow custom security groups

### PR DESCRIPTION
**Pull request by janschumann**
It is great to create a default security group by default. But you may want a little more flexibility. 

This PR allows to disable the default security group and to provide a list of custom  security groups to be added to the es domain.

### CODE REVIEW

**Comment by aknysh** [comment]
@janschumann  can you please address the comments so we could merge the PR, thanks

**Comment by aknysh** [comment]
@janschumann  thanks!
did you provision it on AWS with your changes?
for some reason, our tests on this PR are failing with the error (ran many times):

```
TestExamplesComplete 2019-10-24T13:52:17Z command.go:121: Error: Error creating ElasticSearch domain: ValidationException: Authentication error                  
TestExamplesComplete 2019-10-24T13:52:17Z command.go:121:       status code: 400, request id: 31f17bdd-f665-11e9-9d0c-d72ced69010a                               
TestExamplesComplete 2019-10-24T13:52:17Z command.go:121:                                                                                                        
TestExamplesComplete 2019-10-24T13:52:17Z command.go:121:   on ../../main.tf line 102, in resource "aws_elasticsearch_domain" "default":                         
TestExamplesComplete 2019-10-24T13:52:17Z command.go:121:  102: resource "aws_elasticsearch_domain" "default" {                                                  

```

See https://g.codefresh.io/public/accounts/cloudposse/builds/5db1aba9801258002f6fdded

But the master branch provisions OK using the same tests (just tested).
Maybe it's related to the changes, maybe something else.
Can you take a look?

Thanks

**Comment by janschumann** [comment]
@aknysh Thats weird ... Authentication error? 

We are using this PR in our configuration. 

I will investigate further.

**Comment by maximmi** [comment]
@janschumann any new on this?

**Comment by Gowiem** [comment]
@janschumann Sadly, it looks like this PR conflicts pretty heavily with some other work that just got merged. I tried to resolve the conflicts, but looks like it will need some more individual care. Mind taking a crack at it and we'll get it merged once things are cleared up?

**Comment by aknysh** [comment]
@janschumann please rebase

**Pull request closed without merging**
